### ISSUE TITLE
Add ui for chat threads, make them selectable

### ISSUE THREAD

**Issue by rollie42** [Hack-Weekly/lavender-snake#26]
Each previous chat needs a UI, showing who is involved in the chat, how many new messages, etc (see figma). These should be selected, and should update the chat content based on selected chat.

Probably change the 'currentlySelectedChat' field from an index into an array to an id, and each chat group  should have a randomly generated id to facilitate this.

**Comment by ajoykumardas12** [comment]
Tasks pending: 
> Show how many new messages
> Update chat screen on chat group select
